// Generated by CoffeeScript 1.9.3
(function() {
  var StorageEngine, fs, loadEndpoints, path, port, restify, se, seConfig, server, sprocDirectory;

  restify = require("restify");

  fs = require('fs');

  path = require('path');

  StorageEngine = require(path.join(__dirname, 'src', 'StorageEngine'));

  loadEndpoints = require(path.join(__dirname, 'src', 'loadEndpoints'));

  se = null;

  seConfig = {
    terminate: false,
    debug: false
  };

  port = process.env.PORT || 1338;

  server = restify.createServer({
    name: 'temporalize',
    version: "0.1.0"
  });

  server.use(restify.authorizationParser());

  server.use(restify.bodyParser({
    mapParams: false
  }));

  server.use(restify.queryParser({
    mapParams: false
  }));

  server.locals = {};

  sprocDirectory = path.join(__dirname, 'sprocs');

  se = new StorageEngine(seConfig, function() {
    return loadEndpoints(server, se, function(err) {
      if (err != null) {
        console.dir(err);
        throw new Error("Got error trying to loadEndpoints");
      }
      return server.listen(port, function() {
        return console.log("%s listening at %s", server.name, server.url);
      });
    });
  });

}).call(this);
